# Generated by Django 5.1.6 on 2025-03-02 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, help_text='Для мягкого удаления', verbose_name='Активен')),
                ('notification_type', models.CharField(choices=[('order_created', 'Создание заказа'), ('payment_received', 'Получение платежа'), ('order_shipped', 'Отправка товара'), ('advertisement', 'Рекламная рассылка'), ('system_alert', 'Системное уведомление')], max_length=20, verbose_name='Тип уведомления')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('is_broadcast', models.BooleanField(default=False, verbose_name='Массовая рассылка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
                'indexes': [models.Index(fields=['notification_type', 'is_sent'], name='notificatio_notific_4caeff_idx'), models.Index(fields=['scheduled_time'], name='notificatio_schedul_c4290c_idx')],
            },
        ),
    ]
