services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME:-mydb}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  admin_panel:
    build:
      context: ./admin_panel
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
    depends_on:
      - postgres
    networks:
      - app_network

  bot_project:
    build:
      context: ./bot_project
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - YOOMONEY_KEY=${YOOMONEY_KEY}
      - YOOMONEY_ID=${YOOMONEY_ID}
    ports:
      - "8080:8080"
    volumes:
      - ./media:/app/media
    depends_on:
      - postgres
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx.conf
      - ./media:/app/media
    depends_on:
      - admin_panel
      - bot_project
    networks:
      - app_network

volumes:
  postgres_data:
  media:


networks:
  app_network:
    driver: bridge
