# services:
#   django:
#     build: ./admin_panel
#     volumes:
#       - ./media:/app/media # Монтируем папку media
#     env_file:
#       - .env
#     ports:
#       - "8000:8000"
#     depends_on:
#       - postgres

#   bot:
#     build: ./bot_app
#     volumes:
#       - ./media:/app/media # Монтируем ту же папку media
#     env_file:
#       - .env
#     depends_on:
#       - django
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

    # volumes:
    #   postgres_data:
    #   media:
    # Volume для медиафайлов








    # version: '3.8'

    # services:
    #   web:
    #     build: .
    #     volumes:
    #       - .:/app
    #       - ./media:/app/media  # Монтируем папку media
    #     env_file:
    #       - .env
    #     ports:
    #       - "8000:8000"
    #     depends_on:
    #       - db

    #   db:
    #     image: postgres:13
    #     environment:
    #       POSTGRES_DB: ${POSTGRES_DB}
    #       DB_USER: ${DB_USER}
    #       DB_PASSWORD: ${DB_PASSWORD}
    #     volumes:
    #       - postgres_data:/var/lib/postgresql/data/

    # volumes:
    #   postgres_data:
