services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  admin_panel:
    build:
      context: ./admin_panel
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             gunicorn admin_panel.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./admin_panel:/app
      - media_volume:/app/media
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DJANGO_DEBUG}
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  bot_project:
    build:
      context: ./bot_project
      dockerfile: Dockerfile
    command: python bot.py
    volumes:
      - ./bot_project:/app
      - media_volume:/app/media
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      - postgres

volumes:
  postgres_data:
  media_volume:
