# Generated by Django 5.1.6 on 2025-03-05 23:40

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, help_text='Для мягкого удаления', verbose_name='Активен')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Логин в Telegram')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, help_text='Для мягкого удаления', verbose_name='Активен')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион/Область')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('building', models.CharField(max_length=20, verbose_name='Дом/Строение')),
                ('apartment', models.CharField(blank=True, max_length=20, null=True, verbose_name='Квартира/Офис')),
                ('postal_code', models.CharField(max_length=20, validators=[apps.core.validators.validate_postal_code], verbose_name='Почтовый индекс')),
                ('phone', models.CharField(max_length=20, validators=[apps.core.validators.validate_phone], verbose_name='Телефон')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
                'ordering': ['-is_primary', '-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'is_primary'], name='core_delive_user_id_5014fe_idx'), models.Index(fields=['postal_code'], name='core_delive_postal__026742_idx')],
            },
        ),
    ]
